import { defineApp } from "convex/server";
import resend from "@convex-dev/resend/convex.config.js";
import workflow from "@convex-dev/workflow/convex.config";
import rateLimiter from "@convex-dev/rate-limiter/convex.config";
import aggregate from "@convex-dev/aggregate/convex.config";
const app = defineApp();
app.use(resend);
app.use(workflow);
app.use(rateLimiter);
app.use(aggregate, { name: "eventsMetrics" });
app.use(aggregate, { name: "registrationsMetrics" });
app.use(aggregate, { name: "submissionsMetrics" });
app.use(aggregate, { name: "emailDeliveriesMetrics" });
export default app;
