allowBuilds:
  esbuild: true
  '@reown/appkit': false
  secp256k1: false
  bufferutil: false
  utf-8-validate: false
patchedDependencies:
  '@jsr/creit-tech__stellar-wallets-kit@2.7.0': patches/@jsr__creit-tech__stellar-wallets-kit@2.7.0.patch
